### ISSUE TITLE
Error Encountered When Running machu.1.tip.resp

### ISSUE THREAD

**Issue by Xinru99** [wxguillo/machuruku#11]
Dear Wilson Guillory,
I'm encountering an error when running the machu.1.tip.resp function in R. Specifically, the error message states:
Error: if (abs(galton) < max.GB) interp.alpha(abs(galton)) else {: Needs TRUE/FALSE values where missing values are not allowed
7. galton2alpha(galton, move.in = TRUE)
6. st.prelimFit(x, y, verbose = as.numeric(trace), SN = TRUE)
5. sn.mple(x, y, cp, w, penalty, trace, contr$opt.method, contr$control)
4. selm.fit(x, y, family = family, start, w = w, fixed.param = fixed.param,
offset = offset, selm.control = contr)
3. selm(eval(parse(text = i)) ~ 1, data = in.pres)
2. extractSECdistr(selm(eval(parse(text = i)) ~ 1, data = in.pres))
1. machu.1.tip.resp(occ, current)

It appears that there's an issue with the conditional statement in the code, specifically involving the galton and max.GB variables. The error message indicates that it requires TRUE/FALSE values where missing values are not allowed.

Attached is the distribution data I used. I would greatly appreciate any assistance in troubleshooting this error. 
[distribution.csv](https://github.com/user-attachments/files/15574269/distribution.csv)

Thank you for your help in advance!

Best regards,
Xinru

**Comment by wxguillo** [comment]
Hi Xinru, thanks for bringing this to my attention. I used your data to figure out that the issue was occurring for species with very small amounts of occurrence points in environmentally similar localities. For some reason, the sn::selm function that machu.1.tip.resp uses to estimate climate response curves doesn't work for some of these cases. I wasn't able to find a very elegant solution, so for now I introduced a "jitter" argument to the machu.1.tip.resp function, which adds some very slight variation to the sampled climate response values before passing them to selm, which seems to solve the problem. After running the function as follows:
```
t <- machu.1.tip.resp(occ, r, verbose = T, jitter=T)
```
with `jitter=T`, I was able to process all of your taxa. I passed this update to Github, so you'll have to reinstall the package to use it.
Best,
Wilson
