### ISSUE TITLE
Loading tree

### ISSUE THREAD

**Issue by ybl18231302914** [wxguillo/machuruku#12]
Dear Wilson Guillory,
I'm encountering an error when loading tree in R. Specifically, the error message states:
> tree <- read.nexus("test2.treefile")
Error in start:end : 参数长度为零
Secondly, I noticed that the paleoclimatic library used in our software is only up to the Pliocene, and I want to know how to deal with it if I want to speculate further, such as the Cretaceous Jurassic?
This is my first time using R, and I may have a lot of problems to trouble you later.
I want to show you my file, but it doesn't support the treefile format.This isn't my full tree either, I just wanted to take my data and test run your R package first.
Thank you very much
<img width="960" alt="截图20241015125816" src="https://github.com/user-attachments/assets/9ee6bcba-8179-4127-b43a-977a4ff80a1a">
<img width="959" alt="截图20241015125755" src="https://github.com/user-attachments/assets/594a77ed-9e0c-4a00-9e6d-622c54f1cd33">

**Comment by wxguillo** [comment]
Hi, 
My translation of your error message is "The parameter length is zero," is that about right? To me it sounds like the treefile you are attempting to load with read.nexus doesn't have any data in it. You can try the alternative function read.tree, but this is probably an issue with your input file rather than with machuruku itself, which I can't really help you with.
Regarding your second question, unfortunately I don't know of any paleoclimate layers that go back to the Mesozoic (if you do, I want to hear about them!). The oldest dataset I know of is Paleo-PGEM-Series, which extends back to 5 mya at 1000-yr intervals, though with much lower resolution than Paleoclim. This is unfortunately a hard limitation of the method, as we are reliant on paleoclimate modeling to get paleoclimate estimates to project ancestral niches into, and estimating climate for time periods that long ago is extraordinarily difficult or impossible. In the Mesozoic, the continents themselves were in very different configurations!
There are ways of getting around this if you are willing to compromise. You can still estimate ancestral niches for very old trees, you just won't be able to project them into paleoclimate past certain ages. You could still project them into modern climate, and compare taxa from different times in the same climatic framework. Or you can go nonspatial and just view the response curves for each node with machu.respplot. 
Hope this helps,
Wilson

**Comment by ybl18231302914** [comment]
Thank you for your reply, it can be loaded with read.tree.I'll consider your suggestion and ask you if I have any questions in the future.
