### ISSUE TITLE
Unable to get CI for ancestral niche reconstruction 

### ISSUE THREAD

**Issue by anthonysnead** [wxguillo/machuruku#6]
Hello,
I had no errors getting the response curves for the tips of the trees, but I am getting two warning messages when I attempt to do machu.2.ace:

1: In sqrt(1/out$hessian) : NaNs produced
2: In nlm(function(p) minus.REML.BM(p), p = rep(mu[1], nb.node),  ... :
  NA/Inf replaced by maximum positive value

Warning 2 is repeated for all of the variables used. It provide me with estimates; however, it does not estimate the CI of any parameter. I thought it may have to do with a polytomy in the tree or that it was unrooted. However, I fixed both of those issues, and it still seems to be happening. 

Thank you.

**Comment by wxguillo** [comment]
Hi Anthony. Off the top of my head I'm unsure what could be causing this issue. One other quick tree-related fix to try is using phytools::force.ultrametric to make sure all of the tips in the tree are at the same height. If that doesn't work, you will have to help me replicate the problem by sending your code and files (an RData object would be best) to me at wxg1@rutgers.edu. This could be a bug in my code rather than on your end so it will be helpful for me to fix it.

**Comment by anthonysnead** [comment]
Yeah, I thought the force.ultrametric might fix it to, but when I tested it with is.ultrametric, phytools says it is. I will send it over now because I would love to use the tool.

**Comment by anthonysnead** [comment]
As an update: It was the tree I used. I got a tree from TimeTree5 as a newick file, but the CI estimation did now work properly. Wilson and I still do not know why, but if you have a properly formatted tree, the function will work. Thanks for you help, Wilson!
