### ISSUE TITLE
Advice on machu.3.anc.niche

### ISSUE THREAD

**Issue by Calli-E** [wxguillo/machuruku#9]
Dear WIlson, 

I hope you are doing very well. I have been following the tutorial with my data. I am using four timeslices. I have the current climate rasters and the past rasters in the directory, just like in the example with your data in the tutorial. Although all the functions run smoothly when using the machu.3.anc.niche function, the resulting rasters only have zero values for all timeslices. Here is an example with a single timeslice:

resp <- machu.1.tip.resp(nuevo_df, clim)
ace_3.3 <- machu.2.ace(resp, tree2, timeslice=3.3)
mod_3.3 <- machu.3.anc.niche(ace_3.3, M2_clim2, verbose=T)

> M2_clim2
class      : RasterStack 
dimensions : 1831, 3060, 5602860, 5  (nrow, ncol, ncell, nlayers)
resolution : 0.0417, 0.0417  (x, y)
extent     : -180, -52.398, 6.9808, 83.3335  (xmin, xmax, ymin, ymax)
crs        : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
names      :      bio_1,     bio_10,     bio_12,     bio_15,      bio_8 
min values : -291.62364, -102.86522,   16.31636,    8.00000, -201.34466 
max values :   303.7748,   406.0000,  5913.4889,   186.0268,   382.9636 

> mod_3.3 <- machu.3.anc.niche(ace_3.3, M2_clim2, verbose=T)
[1] "Did not detect uncertainty samples in 'ace' ('unc' in machu.2.ace())."
[1] "Solo RasterStack converted to SpatRaster format."
[1] "Associating scenarios ('ace') with rastersets ('clim') (numbers are indices, rows are associations):"
     clim ace
[1,]    1   1
[1] "Processed scenario 1"
> mod_3.3
$timeslice_3.3
$timeslice_3.3$`Node3-Agkistrodon_bilineatus`
class       : SpatRaster 
dimensions  : 1831, 3060, 1  (nrow, ncol, nlyr)
resolution  : 0.0417, 0.0417  (x, y)
extent      : -180, -52.398, 6.9808, 83.3335  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
source(s)   : memory
varname     : r_tmp_2024-04-25_103316.772623_12028_25776 
name        : Node3-Agkistrodon_bilineatus 
min value   :                            0 
max value   :                            0 

$timeslice_3.3$`Node4-Mixcoatlus_barbouri`
class       : SpatRaster 
dimensions  : 1831, 3060, 1  (nrow, ncol, nlyr)
resolution  : 0.0417, 0.0417  (x, y)
extent      : -180, -52.398, 6.9808, 83.3335  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
source(s)   : memory
varname     : r_tmp_2024-04-25_103316.772623_12028_25776 
name        : Node4-Mixcoatlus_barbouri 
min value   :                         0 
max value   :                         0 

$timeslice_3.3$`Node4-Ophryacus_undulatus`
class       : SpatRaster 
dimensions  : 1831, 3060, 1  (nrow, ncol, nlyr)
resolution  : 0.0417, 0.0417  (x, y)
extent      : -180, -52.398, 6.9808, 83.3335  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
source(s)   : memory
varname     : r_tmp_2024-04-25_103316.772623_12028_25776 
name        : Node4-Ophryacus_undulatus 
min value   :                         0 
max value   :                         0 

$timeslice_3.3$`Node7-Cerrophidion_godmani`
class       : SpatRaster 
dimensions  : 1831, 3060, 1  (nrow, ncol, nlyr)
resolution  : 0.0417, 0.0417  (x, y)
extent      : -180, -52.398, 6.9808, 83.3335  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
source(s)   : memory
varname     : r_tmp_2024-04-25_103316.772623_12028_25776 
name        : Node7-Cerrophidion_godmani 
min value   :                          0 
max value   :                          0 

I have tried using a SpatRaster list getting the same result. Do you have any idea why this could be happening?

**Comment by wxguillo** [comment]
Hi, thanks for trying the package. When the ancestral niche models are zero across the board, it means that Machuruku recovered very little suitable habitat for some of your climate variables. In machu.3.anc.niche, Machuruku first calculates suitability for each individual climate variable by itself. Then, Machuruku uses a "bounding-box" algorithm to construct an ancestral niche model, taking, for each pixel, the lowest value across the per-climate-variable suitabilities. If even one of these per-climate-variable suitability rasters is all zero, then the final output will also be all zero. 
![fig1](https://github.com/wxguillo/machuruku/assets/18176870/7349fe26-1c36-4cc3-8a51-d2a1b1b5cd2a)
In this example (from someone who had a similar issue recently), bio1, bio11, bio4, and bio8 all are mostly zeroes. You can see that, for every single land pixel, the lowest value across all climate variables is zero. Basically, the algorithm is working properly, it's the data that are the problem. You can get around this by using fewer or different climate variables. In this case, removing bio1, bio11, bio4, and bio8 from the dataset offered workable results. I see you're already down to 5 layers, so you might want to try swapping different variables out for other ones, instead of removing more. 

If you really want, I happen to know you can change "min" in line 1454 of the code (v 2.0.2) to "mean" to circumvent this issue completely by just calculating the mean value for each pixel across the per-climate-variable suitabilities, instead of the minimum. It would just cause some niche modelers to have meltdowns over the methodology :)

**Comment by Calli-E** [comment]
Great, thank you for your quick response! I'll try both alternatives! :)
